using _3S.CoDeSys.Core.Components;

namespace _3S.CoDeSys.Core.LanguageModel
{
	[TypeGuid("{bffb3c53-f105-4e85-aba2-e30df579d75f}")]
	public enum Operator
	{
		[ReleasedEnumMember]
		None,
		[ReleasedEnumMember]
		__Reloc,
		[ReleasedEnumMember]
		__Copy,
		[ReleasedEnumMember]
		__Lazy,
		[ReleasedEnumMember]
		Any,
		[ReleasedEnumMember]
		AnyBit,
		[ReleasedEnumMember]
		AnyDate,
		[ReleasedEnumMember]
		AnyInt,
		[ReleasedEnumMember]
		AnyNum,
		[ReleasedEnumMember]
		AnyReal,
		[ReleasedEnumMember]
		Bit,
		[ReleasedEnumMember]
		Bool,
		[ReleasedEnumMember]
		Byte,
		[ReleasedEnumMember]
		Word,
		[ReleasedEnumMember]
		DWord,
		[ReleasedEnumMember]
		LWord,
		[ReleasedEnumMember]
		SInt,
		[ReleasedEnumMember]
		Int,
		[ReleasedEnumMember]
		DInt,
		[ReleasedEnumMember]
		LInt,
		[ReleasedEnumMember]
		USInt,
		[ReleasedEnumMember]
		UInt,
		[ReleasedEnumMember]
		UDInt,
		[ReleasedEnumMember]
		ULInt,
		[ReleasedEnumMember]
		Real,
		[ReleasedEnumMember]
		LReal,
		[ReleasedEnumMember]
		String,
		[ReleasedEnumMember]
		WString,
		[ReleasedEnumMember]
		Time,
		[ReleasedEnumMember]
		LTime,
		[ReleasedEnumMember]
		Date,
		[ReleasedEnumMember]
		DateAndTime,
		[ReleasedEnumMember]
		TimeOfDay,
		[ReleasedEnumMember]
		Adr,
		[ReleasedEnumMember]
		BitAdr,
		[ReleasedEnumMember]
		IndexOf,
		[ReleasedEnumMember]
		SizeOf,
		[ReleasedEnumMember]
		Ini,
		[ReleasedEnumMember]
		Abs,
		[ReleasedEnumMember]
		Limit,
		[ReleasedEnumMember]
		Min,
		[ReleasedEnumMember]
		Max,
		[ReleasedEnumMember]
		Trunc,
		[ReleasedEnumMember]
		Mux,
		[ReleasedEnumMember]
		Sel,
		[ReleasedEnumMember]
		Rol,
		[ReleasedEnumMember]
		Ror,
		[ReleasedEnumMember]
		Shl,
		[ReleasedEnumMember]
		Shr,
		[ReleasedEnumMember]
		Exp,
		[ReleasedEnumMember]
		Expt,
		[ReleasedEnumMember]
		Sqrt,
		[ReleasedEnumMember]
		Ln,
		[ReleasedEnumMember]
		Log,
		[ReleasedEnumMember]
		Sin,
		[ReleasedEnumMember]
		Cos,
		[ReleasedEnumMember]
		Tan,
		[ReleasedEnumMember]
		ASin,
		[ReleasedEnumMember]
		ACos,
		[ReleasedEnumMember]
		ATan,
		[ReleasedEnumMember]
		Action,
		[ReleasedEnumMember]
		Array,
		[ReleasedEnumMember]
		Params,
		[ReleasedEnumMember]
		At,
		[ReleasedEnumMember]
		By,
		[ReleasedEnumMember]
		Case,
		[ReleasedEnumMember]
		Constant,
		[ReleasedEnumMember]
		Do,
		[ReleasedEnumMember]
		Else,
		[ReleasedEnumMember]
		Elsif,
		[ReleasedEnumMember]
		EndAction,
		[ReleasedEnumMember]
		EndCase,
		[ReleasedEnumMember]
		EndFor,
		[ReleasedEnumMember]
		EndFunction,
		[ReleasedEnumMember]
		EndFunctionBlock,
		[ReleasedEnumMember]
		EndIf,
		[ReleasedEnumMember]
		EndProgram,
		[ReleasedEnumMember]
		EndRepeat,
		[ReleasedEnumMember]
		EndStruct,
		[ReleasedEnumMember]
		EndUnion,
		[ReleasedEnumMember]
		EndType,
		[ReleasedEnumMember]
		EndVar,
		[ReleasedEnumMember]
		EndWhile,
		[ReleasedEnumMember]
		Exit,
		[ReleasedEnumMember]
		Continue,
		[ReleasedEnumMember]
		For,
		[ReleasedEnumMember]
		From,
		[ReleasedEnumMember]
		Function,
		[ReleasedEnumMember]
		FunctionBlock,
		[ReleasedEnumMember]
		If,
		[ReleasedEnumMember]
		Of,
		[ReleasedEnumMember]
		Persistent,
		[ReleasedEnumMember]
		Pointer,
		[ReleasedEnumMember]
		Program,
		[ReleasedEnumMember]
		ReadOnly,
		[ReleasedEnumMember]
		ReadWrite,
		[ReleasedEnumMember]
		Repeat,
		[ReleasedEnumMember]
		Retain,
		[ReleasedEnumMember]
		Return,
		[ReleasedEnumMember]
		Struct,
		[ReleasedEnumMember]
		Union,
		[ReleasedEnumMember]
		Then,
		[ReleasedEnumMember]
		To,
		[ReleasedEnumMember]
		Type,
		[ReleasedEnumMember]
		Until,
		[ReleasedEnumMember]
		Var,
		[ReleasedEnumMember]
		VarAccess,
		[ReleasedEnumMember]
		VarConfig,
		[ReleasedEnumMember]
		VarExternal,
		[ReleasedEnumMember]
		VarGlobal,
		[ReleasedEnumMember]
		VarInput,
		[ReleasedEnumMember]
		VarInOut,
		[ReleasedEnumMember]
		VarOutput,
		[ReleasedEnumMember]
		VarTemp,
		[ReleasedEnumMember]
		VarStat,
		[ReleasedEnumMember]
		While,
		[ReleasedEnumMember]
		Extends,
		[ReleasedEnumMember]
		Implements,
		[ReleasedEnumMember]
		Method,
		[ReleasedEnumMember]
		Interface,
		[ReleasedEnumMember]
		This,
		[ReleasedEnumMember]
		Super,
		[ReleasedEnumMember]
		Add,
		[ReleasedEnumMember]
		Sub,
		[ReleasedEnumMember]
		Mul,
		[ReleasedEnumMember]
		Div,
		[ReleasedEnumMember]
		Mod,
		[ReleasedEnumMember]
		And,
		[ReleasedEnumMember]
		AndN,
		[ReleasedEnumMember]
		Or,
		[ReleasedEnumMember]
		OrN,
		[ReleasedEnumMember]
		Xor,
		[ReleasedEnumMember]
		XorN,
		[ReleasedEnumMember]
		Not,
		[ReleasedEnumMember]
		Eq,
		[ReleasedEnumMember]
		Ne,
		[ReleasedEnumMember]
		Ge,
		[ReleasedEnumMember]
		Gt,
		[ReleasedEnumMember]
		Le,
		[ReleasedEnumMember]
		Lt,
		[ReleasedEnumMember]
		Cal,
		[ReleasedEnumMember]
		CalC,
		[ReleasedEnumMember]
		CalCN,
		[ReleasedEnumMember]
		Jmp,
		[ReleasedEnumMember]
		JmpC,
		[ReleasedEnumMember]
		JmpCN,
		[ReleasedEnumMember]
		Ret,
		[ReleasedEnumMember]
		RetC,
		[ReleasedEnumMember]
		RetCN,
		[ReleasedEnumMember]
		Ld,
		[ReleasedEnumMember]
		LdN,
		[ReleasedEnumMember]
		St,
		[ReleasedEnumMember]
		StN,
		[ReleasedEnumMember]
		Move,
		[ReleasedEnumMember]
		TestAndSet,
		[ReleasedEnumMember]
		R,
		[ReleasedEnumMember]
		S,
		[ReleasedEnumMember]
		Plus,
		[ReleasedEnumMember]
		Minus,
		[ReleasedEnumMember]
		Times,
		[ReleasedEnumMember]
		Power,
		[ReleasedEnumMember]
		Divide,
		[ReleasedEnumMember]
		Period,
		[ReleasedEnumMember]
		Colon,
		[ReleasedEnumMember]
		Assign,
		[ReleasedEnumMember]
		SetAssign,
		[ReleasedEnumMember]
		ResetAssign,
		[ReleasedEnumMember]
		LeftParenthesis,
		[ReleasedEnumMember]
		RightParenthesis,
		[ReleasedEnumMember]
		LeftBracket,
		[ReleasedEnumMember]
		RightBracket,
		[ReleasedEnumMember]
		Comma,
		[ReleasedEnumMember]
		Semicolon,
		[ReleasedEnumMember]
		Range,
		[ReleasedEnumMember]
		AssignOut,
		[ReleasedEnumMember]
		Less,
		[ReleasedEnumMember]
		Greater,
		[ReleasedEnumMember]
		LessEqual,
		[ReleasedEnumMember]
		GreaterEqual,
		[ReleasedEnumMember]
		Equal,
		[ReleasedEnumMember]
		NotEqual,
		[ReleasedEnumMember]
		Ampersand,
		[ReleasedEnumMember]
		VerticalLine,
		[ReleasedEnumMember]
		DeRef,
		[ReleasedEnumMember]
		Conversion,
		[ReleasedEnumMember]
		RefAssign,
		[ReleasedEnumMember]
		Reference,
		[ReleasedEnumMember]
		Property,
		[ReleasedEnumMember]
		TruncInt,
		[ReleasedEnumMember]
		FupAssign,
		[ReleasedEnumMember]
		__LocalOffset,
		[ReleasedEnumMember]
		__VarInfo,
		[ReleasedEnumMember]
		__SystemScope,
		[ReleasedEnumMember]
		__TypeOf,
		[ReleasedEnumMember]
		__CRC,
		[ReleasedEnumMember]
		__MaxOffset,
		[ReleasedEnumMember]
		__Init,
		[ReleasedEnumMember]
		__IsValidRef,
		[ReleasedEnumMember]
		__QueryInterface,
		[ReleasedEnumMember]
		__QueryPointer,
		[ReleasedEnumMember]
		__New,
		[ReleasedEnumMember]
		__Delete,
		[ReleasedEnumMember]
		__Cast,
		[ReleasedEnumMember]
		__AdrInst,
		[ReleasedEnumMember]
		__RefAdr,
		[ReleasedEnumMember]
		__Wait,
		[ReleasedEnumMember]
		SafeBool,
		[ReleasedEnumMember]
		SafeByte,
		[ReleasedEnumMember]
		SafeUSInt,
		[ReleasedEnumMember]
		SafeSInt,
		[ReleasedEnumMember]
		SafeWord,
		[ReleasedEnumMember]
		SafeUInt,
		[ReleasedEnumMember]
		SafeInt,
		[ReleasedEnumMember]
		SafeDWord,
		[ReleasedEnumMember]
		SafeUDInt,
		[ReleasedEnumMember]
		SafeTime,
		[ReleasedEnumMember]
		SafeDInt,
		[ReleasedEnumMember]
		SafeLWord,
		[ReleasedEnumMember]
		SafeULInt,
		[ReleasedEnumMember]
		SafeLInt,
		[ReleasedEnumMember]
		__BitOffset,
		[ReleasedEnumMember]
		__FCall,
		[ReleasedEnumMember]
		__PropertyInfo,
		[ReleasedEnumMember]
		Class,
		[ReleasedEnumMember]
		Abstract,
		[ReleasedEnumMember]
		Override,
		[ReleasedEnumMember]
		Public,
		[ReleasedEnumMember]
		Private,
		[ReleasedEnumMember]
		Protected,
		[ReleasedEnumMember]
		Internal,
		[ReleasedEnumMember]
		Final,
		[ReleasedEnumMember]
		__XWord,
		[ReleasedEnumMember]
		__UXInt,
		[ReleasedEnumMember]
		__MemorySet,
		[ReleasedEnumMember]
		And_Then,
		[ReleasedEnumMember]
		Or_Else,
		[ReleasedEnumMember]
		__GetLTick,
		[ReleasedEnumMember]
		__XInt,
		[ReleasedEnumMember]
		__Try,
		[ReleasedEnumMember]
		__EndTry,
		[ReleasedEnumMember]
		__Catch,
		[ReleasedEnumMember]
		__Finally,
		[ReleasedEnumMember]
		__Throw,
		[ReleasedEnumMember]
		__XString,
		[ReleasedEnumMember]
		VarInst,
		[ReleasedEnumMember]
		__CheckLicense,
		[ReleasedEnumMember]
		__CallInitFunction,
		[ReleasedEnumMember]
		__LateCompiledExpr,
		[ReleasedEnumMember]
		LowerBound,
		[ReleasedEnumMember]
		UpperBound,
		[ReleasedEnumMember]
		AnyString,
		[ReleasedEnumMember]
		__PoolScope,
		[ReleasedEnumMember]
		__CheckLicenseBit,
		[ReleasedEnumMember]
		__XAdd,
		[ReleasedEnumMember]
		__MemoryBarrier,
		[ReleasedEnumMember]
		__CurrentTask,
		[ReleasedEnumMember]
		__CompareAndSwap,
		[ReleasedEnumMember]
		__Vector,
		[ReleasedEnumMember]
		__vcAdd,
		[ReleasedEnumMember]
		__vcSub,
		[ReleasedEnumMember]
		__vcMul,
		[ReleasedEnumMember]
		__vcDiv,
		[ReleasedEnumMember]
		__vcDot,
		[ReleasedEnumMember]
		__vcSqrt,
		[ReleasedEnumMember]
		__vcMin,
		[ReleasedEnumMember]
		__vcMax,
		[ReleasedEnumMember]
		__vcSetReal,
		[ReleasedEnumMember]
		__vcSetLReal,
		[ReleasedEnumMember]
		__vcLoadReal,
		[ReleasedEnumMember]
		__vcLoadLReal,
		[ReleasedEnumMember]
		__vcStore,
		[ReleasedEnumMember]
		Hash,
		[ReleasedEnumMember]
		SafeReal,
		[ReleasedEnumMember]
		SafeLReal,
		[ReleasedEnumMember]
		LDate,
		[ReleasedEnumMember]
		LDateAndTime,
		[ReleasedEnumMember]
		LTimeOfDay,
		[ReleasedEnumMember]
		XSizeOf,
		[ReleasedEnumMember]
		__PouName,
		[ReleasedEnumMember]
		__Position,
		[ReleasedEnumMember]
		VarGeneric,
		[ReleasedEnumMember]
		EndMethod,
		[ReleasedEnumMember]
		EndProperty,
		[ReleasedEnumMember]
		EndInterface,
		[ReleasedEnumMember]
		PropertySet,
		[ReleasedEnumMember]
		PropertyGet,
		[ReleasedEnumMember]
		__Begin_Implementation,
		[ReleasedEnumMember]
		Namespace,
		[ReleasedEnumMember]
		EndNamespace,
		[ReleasedEnumMember]
		Overload,
		[ReleasedEnumMember]
		Transition,
		[ReleasedEnumMember]
		EndTransition
	}
}
