using _3S.CoDeSys.Core.Components;

namespace _3S.CoDeSys.Core.LanguageModel
{
	public enum TokenType
	{
		[ReleasedEnumMember]
		None,
		[ReleasedEnumMember]
		Boolean,
		[ReleasedEnumMember]
		Comment,
		[ReleasedEnumMember]
		DocComment,
		[ReleasedEnumMember]
		Pragma,
		[ReleasedEnumMember]
		Date,
		[ReleasedEnumMember]
		DateAndTime,
		[ReleasedEnumMember]
		DirectVariable,
		[ReleasedEnumMember]
		IncompleteDirectVariable,
		[ReleasedEnumMember]
		DoubleByteString,
		[ReleasedEnumMember]
		Duration,
		[ReleasedEnumMember]
		LDuration,
		[ReleasedEnumMember]
		EndOfLine,
		[ReleasedEnumMember]
		Identifier,
		[ReleasedEnumMember]
		Integer,
		[ReleasedEnumMember]
		Operator,
		[ReleasedEnumMember]
		Real,
		[ReleasedEnumMember]
		SingleByteString,
		[ReleasedEnumMember]
		TimeOfDay,
		[ReleasedEnumMember]
		Whitespace,
		[ReleasedEnumMember]
		Error,
		[ReleasedEnumMember]
		End,
		[ReleasedEnumMember]
		XByteString,
		[ReleasedEnumMember]
		LDate,
		[ReleasedEnumMember]
		LTimeOfDay,
		[ReleasedEnumMember]
		LDateAndTime,
		[ReleasedEnumMember]
		Unused,
		[ReleasedEnumMember]
		PartialAccess
	}
}
