using _3S.CoDeSys.Core.Components;

namespace _3S.CoDeSys.Core.LanguageModel
{
	[TypeGuid("{16f7aa24-038f-444e-9d81-b001bc091d35}")]
	public enum TypeClass
	{
		[ReleasedEnumMember]
		Bool,
		[ReleasedEnumMember]
		Bit,
		[ReleasedEnumMember]
		Byte,
		[ReleasedEnumMember]
		Word,
		[ReleasedEnumMember]
		DWord,
		[ReleasedEnumMember]
		LWord,
		[ReleasedEnumMember]
		SInt,
		[ReleasedEnumMember]
		Int,
		[ReleasedEnumMember]
		DInt,
		[ReleasedEnumMember]
		LInt,
		[ReleasedEnumMember]
		USInt,
		[ReleasedEnumMember]
		UInt,
		[ReleasedEnumMember]
		UDInt,
		[ReleasedEnumMember]
		ULInt,
		[ReleasedEnumMember]
		Real,
		[ReleasedEnumMember]
		LReal,
		[ReleasedEnumMember]
		String,
		[ReleasedEnumMember]
		WString,
		[ReleasedEnumMember]
		Time,
		[ReleasedEnumMember]
		Date,
		[ReleasedEnumMember]
		DateAndTime,
		[ReleasedEnumMember]
		TimeOfDay,
		[ReleasedEnumMember]
		Pointer,
		[ReleasedEnumMember]
		Reference,
		[ReleasedEnumMember]
		Subrange,
		[ReleasedEnumMember]
		Enum,
		[ReleasedEnumMember]
		Array,
		[ReleasedEnumMember]
		Params,
		[ReleasedEnumMember]
		Userdef,
		[ReleasedEnumMember]
		None,
		[ReleasedEnumMember]
		Any,
		[ReleasedEnumMember]
		AnyBit,
		[ReleasedEnumMember]
		AnyDate,
		[ReleasedEnumMember]
		AnyInt,
		[ReleasedEnumMember]
		AnyNum,
		[ReleasedEnumMember]
		AnyReal,
		[ReleasedEnumMember]
		Lazy,
		[ReleasedEnumMember]
		LTime,
		[ReleasedEnumMember]
		BitConst,
		[ReleasedEnumMember]
		UXInt,
		[ReleasedEnumMember]
		XWord,
		[ReleasedEnumMember]
		XInt,
		[ReleasedEnumMember]
		XString,
		[ReleasedEnumMember]
		VarLenArray,
		[ReleasedEnumMember]
		AnyString,
		[ReleasedEnumMember]
		__Vector,
		[ReleasedEnumMember]
		LDate,
		[ReleasedEnumMember]
		LDateAndTime,
		[ReleasedEnumMember]
		LTimeOfDay
	}
}
