//! The snippet tables and the exception table of the parity tests.
//!
//! The tables mix snippets that the legacy parser accepts and snippets it
//! rejects: parity means the same verdict, so the rejected ones matter as
//! much as the accepted ones.

use super::{Basis, Exception, Kind};

pub const STATEMENTS: &[&str] = &[
    // Empty forms.
    "",
    "   ",
    ";",
    ";;",
    "(* only a comment *)",
    // Assignment.
    "x := 1;",
    "x:=1;y:=2;",
    "x := y + 1;",
    "x := 1",
    "x := ;",
    "x :=",
    ":= 1;",
    "x = 1;",
    "1 := x;",
    "x + 1;",
    "a := b := c;",
    "a.b := 1;",
    "a[1] := 1;",
    "a[1, 2] := 1;",
    "a.b[1].c := 1;",
    "a^ := 1;",
    "a^.b := 1;",
    "a.b^ := 1;",
    "a[1]^ := 1;",
    "THIS^.x := 1;",
    "THIS := 1;",
    "a.%X3 := TRUE;",
    "a.3 := TRUE;",
    "%IX0.1 := TRUE;",
    "%QW1 := 5;",
    "x := %IX0.0;",
    "x S= y;",
    "x R= y;",
    "x REF= y;",
    "x REF= y.z;",
    "x REF= 1;",
    "x S = y;",
    "x REF = y;",
    "x := REF(y);",
    "x := NULL;",
    "x := y^;",
    "STEP := 1;",
    "ON := 1;",
    "R_EDGE := 1;",
    "F_EDGE := 1;",
    "S := 1;",
    "R := 1;",
    "__CURRENTTASK := 1;",
    "__new := 1;",
    // Calls.
    "f();",
    "f(1, 2);",
    "f(a := 1, b := 2);",
    "f(a => x);",
    "f(NOT a => x);",
    "f(1, a := 2, b => c);",
    "fb(IN := TRUE, PT := T#5s);",
    "inst.Method(1);",
    "THIS^.Method();",
    "SUPER^.Method(x := 1);",
    "a.b.c(1);",
    "a[1](x);",
    "MOD(1, 2);",
    "f(1,);",
    "f(,1);",
    "f(1 2);",
    "f(1);;",
    "f",
    "f(",
    // IF.
    "IF a THEN b := 1; END_IF;",
    "IF a THEN END_IF;",
    "IF a THEN b := 1; ELSE c := 2; END_IF;",
    "IF a THEN b := 1; ELSIF c THEN d := 2; ELSIF e THEN f := 3; ELSE g := 4; END_IF;",
    "IF a THEN IF b THEN c := 1; END_IF; END_IF;",
    "IF a THEN b := 1; END_IF",
    "IF a THEN b := 1; END_IF x := 2;",
    "IF a THEN ELSIF b THEN END_IF;",
    "IF a THEN ELSE END_IF;",
    "IF a THEN b := 1;",
    "IF a b := 1; END_IF;",
    "IF THEN b := 1; END_IF;",
    "END_IF;",
    // CASE.
    "CASE x OF 1: a := 1; 2: b := 2; END_CASE;",
    "CASE x OF 1, 2, 3: a := 1; END_CASE;",
    "CASE x OF 1..5: a := 1; END_CASE;",
    "CASE x OF -1: a := 1; +2: b := 2; END_CASE;",
    "CASE x OF 1: a := 1; ELSE b := 2; END_CASE;",
    "CASE x OF Red: a := 1; Green, Blue: b := 2; END_CASE;",
    "CASE x OF Color#Red: a := 1; END_CASE;",
    "CASE x OF 16#FF: a := 1; END_CASE;",
    "CASE x OF 8#7: a := 1; END_CASE;",
    "CASE x OF 2#1010: a := 1; END_CASE;",
    "CASE x OF A..B: a := 1; END_CASE;",
    "CASE x OF 1..B: a := 1; END_CASE;",
    "CASE x OF 1: END_CASE;",
    "CASE x OF 1: ; END_CASE;",
    "CASE x OF 1: 2: a := 1; END_CASE;",
    "CASE x OF 1, 2: 3: a := 1; END_CASE;",
    "CASE x OF 1: a := 1; ELSE END_CASE;",
    "CASE x OF 1: a := 1; 2: ELSE b := 1; END_CASE;",
    "CASE x OF END_CASE;",
    "CASE x OF 1: a := 1; END_CASE",
    "CASE x OF 1: CASE y OF 2: a := 1; END_CASE; END_CASE;",
    "CASE x OF 1: IF a THEN b := 1; END_IF; 2: c := 1; END_CASE;",
    "CASE x OF 1: IF a THEN b := 1; END_IF 2: c := 1; END_CASE;",
    "CASE x OF 1: CONTINUE; END_CASE;",
    "CASE x OF 1: f(); END_CASE;",
    "CASE x OF 1 a := 1; END_CASE;",
    "CASE x 1: a := 1; END_CASE;",
    "CASE x OF 1: a := 1; END_CASE;;",
    "CASE x OF 1: JMP l; END_CASE;",
    "CASE x OF 1: __WAIT; 2: a := 1; END_CASE;",
    // Loops.
    "FOR i := 1 TO 10 DO a := i; END_FOR;",
    "FOR i := 1 TO 10 BY 2 DO a := i; END_FOR;",
    "FOR i := 10 TO 1 BY -1 DO a := 1; END_FOR;",
    "FOR i := 1 TO 3 DO END_FOR;",
    "FOR i := 1 TO 3 DO ; END_FOR;",
    "FOR a.b := 1 TO 3 DO ; END_FOR;",
    "FOR i := 1 TO 3 DO a := 1; END_FOR",
    "FOR i := 1 DO a := 1; END_FOR;",
    "FOR i := 1 TO DO a := 1; END_FOR;",
    "WHILE a DO b := 1; END_WHILE;",
    "WHILE a DO END_WHILE;",
    "WHILE a DO b := 1; END_WHILE",
    "WHILE a b := 1; END_WHILE;",
    "REPEAT a := 1; UNTIL b END_REPEAT;",
    "REPEAT a := 1; UNTIL b = 1 END_REPEAT",
    "REPEAT UNTIL b END_REPEAT;",
    "REPEAT a := 1; END_REPEAT;",
    "WHILE TRUE DO EXIT; END_WHILE;",
    "WHILE TRUE DO CONTINUE; END_WHILE;",
    "FOR i := 1 TO 3 DO WHILE a DO EXIT; END_WHILE; END_FOR;",
    "EXIT;",
    "EXIT",
    "CONTINUE;",
    "RETURN;",
    "RETURN",
    "RETURN 1;",
    // CODESYS statements.
    "JMP lbl;",
    "JMP (c) lbl;",
    "JMP;",
    "JMP lbl",
    "lbl: x := 1;",
    "lbl:",
    "lbl: ;",
    "lbl: JMP lbl;",
    "a: b: x := 1;",
    "CASE x OF 1: lbl: y := 1; END_CASE;",
    "IF a THEN lbl: x := 1; END_IF;",
    "continue: x := 1;",
    "__new: x := 1;",
    "`esc`: x := 1;",
    "CALC(c, f(1));",
    "CALC(c, f());",
    "CALC(c, a.b());",
    "CALC(c);",
    "CALC c, f();",
    "__WAIT;",
    "__WAIT(c);",
    "__WAIT",
    "__THROW;",
    "__THROW(1);",
    "__THROW",
    "__TRY a := 1; __CATCH b := 2; __ENDTRY;",
    "__TRY a := 1; __CATCH(e) b := 2; __FINALLY c := 3; __ENDTRY;",
    "__TRY a := 1; __CATCH() b := 2; __ENDTRY;",
    "__TRY __ENDTRY;",
    "__TRY a := 1; __FINALLY c := 3; __ENDTRY",
    "__TRY a := 1; __CATCH __CATCH __ENDTRY;",
    "__TRY a := 1;",
    "__CATCH;",
    "__BEGIN_IMPLEMENTATION x := 1;",
    "__BEGIN_IMPLEMENTATION; x := 1;",
    "__BEGIN_IMPLEMENTATION",
    "__BEGIN_IMPLEMENTATION;",
    "x := 1; __BEGIN_IMPLEMENTATION y := 2;",
    // Words that are keywords only in some dialects.
    "continue := 1;",
    "this := 1;",
    "super := 1;",
    "bit := 1;",
    "persistent := 1;",
    "LDT := 1;",
    "ltime := 1;",
    "ref := 1;",
    "null := 1;",
    "params := 1;",
    "pointer := 1;",
    "reference := 1;",
    "interface := 1;",
    "method := 1;",
    "namespace := 1;",
    "union := 1;",
    "jmp := 1;",
    "calc := 1;",
    "__try := 1;",
    "__wait := 1;",
    "and_then := 1;",
    "x := a and_then b;",
    "x := a or_else b;",
    "TIME := 1;",
    "TIME := TIME#5s;",
    "x := TIME();",
    "x := TIME#5s;",
    "TIME();",
    // Comments, pragmas and identifier spellings.
    "x := 1; (* c *)",
    "x := 1; // c",
    "x := 1; /// doc",
    "x := 1; /* c */",
    "x := 1; (* a (* b *) c *)",
    "x := 1; /* a /* b */ c */",
    "{attribute 'x'} x := 1;",
    "x := 1; {pragma}",
    "x := 1; (* unterminated",
    "x := 'unterminated;",
    "`my var` := 1;",
    "my__var := 1;",
    "caf\u{e9} := 1;",
    "__x := 1;",
    "x := ?;",
    "x := 1 # 2;",
    "x := a.%X1;",
    // Strings.
    "x := 'abc';",
    "x := \"wide\";",
    "x := '';",
    "x := 'a$'b';",
    "x := 'bad $Q escape';",
    "x := STRING#'abc';",
    "x := WSTRING#\"abc\";",
    "x := UTF8#'abc';",
    "x := UCHAR#'a';",
    "x := __XSTRING#\"a\";",
    "x := STRING#\"w\";",
    "x := WSTRING#'w';",
    // Block statements without terminators, nested and in sequence.
    "CASE x OF 1,
2:
3..5:
6: y := 1; END_CASE;",
    "CASE x OF 1: y := 1; 2: ELSE END_CASE;",
    "CASE x OF A: B: y := 1; END_CASE;",
    "CASE x OF 1: y := 1; END_CASE; z := 1;",
    "CASE x OF 1: y := 1; END_CASE z := 1;",
    "IF a THEN CASE x OF 1: END_CASE END_IF",
    "IF a THEN b := 1; END_IF
IF c THEN d := 2; END_IF
",
    "WHILE a DO IF b THEN c := 1; END_IF END_WHILE",
    "REPEAT IF a THEN b := 1; END_IF UNTIL c END_REPEAT",
    "FOR i := 1 TO 3 DO FOR j := 1 TO 3 DO a := 1; END_FOR END_FOR",
    "x := 1; END_IF",
    "lbl: IF a THEN b := 1; END_IF",
    "__TRY a := 1; __CATCH b := 2; __ENDTRY x := 3;",
    "__TRY __CATCH (e) __ENDTRY;",
    "CASE x OF 1: IF a THEN b := 1; ELSE c := 1; END_IF; END_CASE;",
    "CASE x OF 1: WHILE a DO b := 1; END_WHILE 2: c := 1; END_CASE;",
    "CASE x OF 1: __TRY a := 1; __ENDTRY 2: c := 1; END_CASE;",
    "x := f(a := 1, b => c);",
    "; __BEGIN_IMPLEMENTATION x := 1;",
    "lbl: __BEGIN_IMPLEMENTATION x := 1;",
    "x := 1;__BEGIN_IMPLEMENTATION y := 2;",
    // Keywords in lower and mixed case.
    "if a then b := 1; elsif c then d := 2; else e := 3; end_if;",
    "Case x Of 1: a := 1; End_Case;",
    "for i := 1 to 3 by 1 do a := 1; end_for;",
    "while a do b := 1; end_while;",
    "repeat a := 1; until b end_repeat;",
    "x := a mod b;",
    "x := not a;",
    "x := a MOD b;",
    "x := NOT a;",
    "not := 1;",
    "mod := 1;",
    "x := a<>b;",
    "x:=y<z;",
    // Whole programs of statements.
    "x := 1;\r\ny := 2;\r\n",
    "x := 1;\n\n\n(* c *)\n\ty := 2;",
    "a := 1; b := 2; c := 3; d := 4;",
];

pub const EXPRESSIONS: &[&str] = &[
    // Operators and precedence.
    "1",
    "1 + 2",
    "1 - 2 - 3",
    "1 + 2 * 3",
    "1 * 2 + 3",
    "1 ** 2 ** 3",
    "a AND b OR c XOR d",
    "a & b | c",
    "a or b and c",
    "NOT a",
    "NOT NOT a",
    "NOT a = b",
    "NOT a AND b",
    "- a",
    "- - a",
    "-5",
    "--5",
    "+5",
    "+a",
    "+ 5",
    "- 5",
    "a - -5",
    "a + +5",
    "a +5",
    "a -5",
    "-a ** 2",
    "a = b",
    "a <> b",
    "a < b",
    "a <= b",
    "a > b",
    "a >= b",
    "a = b = c",
    "a < b < c",
    "a MOD b",
    "a mod b",
    "a And b",
    "not a",
    "1 +",
    "+",
    "* 1",
    "1 2",
    "a b",
    "a ==  b",
    "a AND",
    "",
    "   ",
    // Parentheses.
    "(a)",
    "((a))",
    "(a + b) * c",
    "(a",
    "a)",
    "()",
    "(,)",
    "(a, b)",
    "a (b)",
    // Operators used as function names.
    "MOD(a, b)",
    "AND(a, b)",
    "OR(a)",
    "XOR(a, b, c)",
    "NOT(a)",
    "NOT(a, b)",
    "NOT()",
    "NOT(a := 1)",
    "NOT (a)",
    "a AND_THEN b",
    "a OR_ELSE b",
    // Calls.
    "f(1)",
    "f()",
    "f(a := 1)",
    "f(a => x)",
    "f(NOT a => x)",
    "f(NOT a => x, b => y)",
    "f(1, a := 2)",
    "f(f(1))",
    "f(1,)",
    "f(a := )",
    "a.b(1)",
    "THIS^.m(1)",
    "a.b.c(1)",
    "a(1)(2)",
    "TIME()",
    "ADR(a)",
    "SIZEOF(a)",
    "SIZEOF(INT)",
    "REF(a)",
    "REF(a.b)",
    "REF(1)",
    "REF a",
    "NULL",
    "__NEW(INT)",
    "__NEW(MyFb)",
    "__NEW(INT, 5)",
    "__NEW(1)",
    "__NEW",
    "__NEW(INT, 5, 6)",
    "__TYPEOF(a)",
    "__TYPEOF(INT)",
    "__TYPEOF(a, b)",
    "__DELETE(p)",
    "__ISVALIDREF(p)",
    "__XADD(a, b)",
    "__new_item",
    "__CURRENTTASK",
    "__CURRENTTASK^.Index",
    // Variables.
    "a",
    "a.b",
    "a[1]",
    "a[1, 2]",
    "a[i + 1]",
    "a[]",
    "a[1",
    "a.b[1].c",
    "a^",
    "a^^",
    "a^.b",
    "a.b^",
    "a[1]^",
    "a^[1]",
    "THIS^",
    "THIS",
    "SUPER^.x",
    "a.1",
    "a.%X3",
    "a.%B1",
    "a.%W2",
    "a.%D1",
    "a.%L1",
    "%IX0.1",
    "%MW4",
    "%I*",
    "S",
    "STEP",
    "ON",
    "R_EDGE",
    "a . b",
    "a [ 1 ]",
    "a. 1",
    "a .%X1",
    "a.",
    "a.STEP",
    "a[1][2]",
    "a^[1]^.b",
    "f(1)^",
    "(a)^",
    "-a[1]",
    "NOT a.b",
    "a.b.c.d",
    "THIS^.x[1]",
    "SUPER^.m(1)",
    "f(a := 1, b => x, NOT c => y)",
    "x ** -2",
    "-(a + b)",
    "a.%W1.%X2",
    "a[1].%B0",
    "m.f(a)^",
    "__CURRENTTASK.Index",
    "STEP.x",
    "a[STEP]",
    "-STEP",
    "`my var`",
    // Numeric literals.
    "1_000",
    "16#FF",
    "16#ff",
    "8#77",
    "2#1010",
    "10#123",
    "5#123",
    "INT#5",
    "INT#-5",
    "INT#+5",
    "INT#- 5",
    "INT# 5",
    "INT #5",
    "SINT#16#FF",
    "UDINT#2#1",
    "DINT#10#5",
    "BYTE#16#FF",
    "BYTE#5",
    "WORD#2#1",
    "DWORD#8#7",
    "LWORD#16#FFFF",
    "BYTE#-5",
    "REAL#1.5",
    "LREAL#1.5e3",
    "REAL#-1.5",
    "REAL#5",
    "1.5",
    "-1.5",
    "+1.5",
    "1.5e3",
    "1.5E-3",
    "1e3",
    "1.",
    ".5",
    "1.5.2",
    // Booleans and strings.
    "TRUE",
    "FALSE",
    "true",
    "BOOL#1",
    "BOOL#0",
    "BOOL#TRUE",
    "BOOL#FALSE",
    "BOOL#2",
    "BOOL#01",
    "BIT#1",
    "BIT#0",
    "BIT#TRUE",
    "'a'",
    "\"a\"",
    "STRING#'a'",
    "WSTRING#\"a\"",
    "UTF8#'x'",
    "UCHAR#'x'",
    "__XSTRING#\"x\"",
    // Durations.
    "T#5s",
    "T#1m30s",
    "T#1.5s",
    "T#100ms",
    "T#-5s",
    "T#1d2h3m4s5ms",
    "T#1d2h3m4s5ms6us7ns",
    "TIME#5s",
    "time#5s",
    "t#5s",
    "T#5",
    "T#5x",
    "T#5s1m",
    "T#1.5m30s",
    "T#1.0m30s",
    "T# 5s",
    "T #5s",
    "T#",
    "LT#5s",
    "LTIME#5s",
    "T#1h_30m",
    "T#1_000ms",
    "T#5S",
    "T#1us",
    "T#1ns",
    "T#5s + T#3s",
    "T#5s < T#3s",
    "T#5m5m",
    // Dates and times of day.
    "TOD#10:00:00",
    "TOD#10:00",
    "TOD#10:00:00.250",
    "TIME_OF_DAY#10:00:00",
    "LTOD#10:00:00",
    "TOD#25:00:00",
    "TOD#10:61",
    "TOD#10:00:61",
    "TOD#10",
    "TOD#10:00:",
    "D#2020-01-01",
    "DATE#2020-01-01",
    "LD#2020-01-01",
    "LDATE#2020-01-01",
    "D#2020-13-01",
    "D#2020-02-30",
    "D#2024-02-29",
    "D#2023-02-29",
    "D#2020-01",
    "D#2020-01-00",
    "DT#2020-01-01-12:00:00",
    "DATE_AND_TIME#2020-01-01-12:00:00",
    "LDT#2020-01-01-12:00:00",
    "DT#2020-01-01",
    "DT#2020-01-01-25:00:00",
];

// ---------------------------------------------------------------------------
// Exceptions
//
// Each entry is a snippet on which the oracle and the new parser disagree,
// and why. The test fails on a difference that is not listed here, and on a
// listed difference that no longer exists.
// ---------------------------------------------------------------------------

const NO_TRAILING_TRIVIA: &str = "the legacy fragment entry does not consume trivia after the last statement (a trailing comment or pragma); inside a POU the same text is accepted";
const NO_LEADING_TRIVIA: &str = "the legacy fragment entry skips leading whitespace but not a leading comment or pragma; inside a POU the same text is accepted";
const NEEDS_ONE_ITEM: &str = "the legacy statement_list rule needs one item, so a fragment of only a comment is rejected; inside a POU an empty body is accepted";
const NO_TERMINATOR_AT_END: &str = "the legacy pipeline inserts the missing `;` only before a following token, so one missing at the very end of the fragment is rejected; inside a POU a token follows";
const SECOND_END_KEYWORD: &str = "the legacy terminator insertion handles an END_* keyword that directly follows another END_* keyword without re-arming itself, so the second one gets no `;` when the source omits it; the new parser makes the `;` optional after every END_* keyword";
const MARKER_AFTER_STATEMENT: &str = "the legacy grammar accepts __BEGIN_IMPLEMENTATION only where the previous list item left no trivia unconsumed, so a marker after a statement and a space is rejected; the new parser accepts the marker as a list item anywhere";
const LONE_CR: &str = "a lone CR is a line break in the lossless lexer (old Mac line endings); the legacy lexer reports it as an unexpected token";
const OSCAT_SEVERAL_PAIRS: &str = "the legacy pre-pass blanks only the first ranged-comment marker pair of a file (and none when the first marker is named END_*), so the body of a later pair is lexed as code and rejected when it holds text that is not tokens; the new parser makes every well-formed pair a region";
const PRAGMA_CONTENT: &str = "the legacy pipeline tokenises the inside of a pragma and rejects a character it does not know; the CST keeps a pragma as one trivia token and does not examine its text";

const fn exception(
    kind: Kind,
    snippet: &'static str,
    basis: Basis,
    reason: &'static str,
) -> Exception {
    Exception {
        kind,
        snippet,
        preset: None,
        legacy: false,
        basis,
        reason,
    }
}

/// The legacy fragment entry rejects `snippet`; the legacy parser inside a
/// POU and the new parser accept it.
const fn fragment_entry(snippet: &'static str, reason: &'static str) -> Exception {
    exception(Kind::Statements, snippet, Basis::FragmentEntry, reason)
}

/// The legacy parser rejects `snippet` and the new one accepts it, on purpose.
const fn accepted_on_purpose(kind: Kind, snippet: &'static str, reason: &'static str) -> Exception {
    exception(kind, snippet, Basis::Deliberate, reason)
}

/// Differences in the statement table, against the legacy fragment entry.
pub const STATEMENT_EXCEPTIONS: &[Exception] = &[
    fragment_entry("(* only a comment *)", NEEDS_ONE_ITEM),
    fragment_entry("x := 1; (* c *)", NO_TRAILING_TRIVIA),
    fragment_entry("x := 1; // c", NO_TRAILING_TRIVIA),
    fragment_entry("x := 1; /// doc", NO_TRAILING_TRIVIA),
    fragment_entry("x := 1; /* c */", NO_TRAILING_TRIVIA),
    fragment_entry("x := 1; (* a (* b *) c *)", NO_TRAILING_TRIVIA),
    fragment_entry("x := 1; {pragma}", NO_TRAILING_TRIVIA),
    fragment_entry("{attribute 'x'} x := 1;", NO_LEADING_TRIVIA),
    fragment_entry("IF a THEN b := 1; END_IF", NO_TERMINATOR_AT_END),
    fragment_entry("CASE x OF 1: a := 1; END_CASE", NO_TERMINATOR_AT_END),
    fragment_entry("FOR i := 1 TO 3 DO a := 1; END_FOR", NO_TERMINATOR_AT_END),
    fragment_entry("WHILE a DO b := 1; END_WHILE", NO_TERMINATOR_AT_END),
    fragment_entry(
        "REPEAT a := 1; UNTIL b = 1 END_REPEAT",
        NO_TERMINATOR_AT_END,
    ),
    fragment_entry(
        "__TRY a := 1; __FINALLY c := 3; __ENDTRY",
        NO_TERMINATOR_AT_END,
    ),
    fragment_entry(
        "IF a THEN b := 1; END_IF\nIF c THEN d := 2; END_IF\n",
        NO_TERMINATOR_AT_END,
    ),
    fragment_entry(
        "REPEAT IF a THEN b := 1; END_IF UNTIL c END_REPEAT",
        NO_TERMINATOR_AT_END,
    ),
    fragment_entry("lbl: IF a THEN b := 1; END_IF", NO_TERMINATOR_AT_END),
    accepted_on_purpose(
        Kind::Statements,
        "x := 1; __BEGIN_IMPLEMENTATION y := 2;",
        MARKER_AFTER_STATEMENT,
    ),
    accepted_on_purpose(
        Kind::Statements,
        "IF a THEN CASE x OF 1: END_CASE END_IF",
        SECOND_END_KEYWORD,
    ),
    accepted_on_purpose(
        Kind::Statements,
        "WHILE a DO IF b THEN c := 1; END_IF END_WHILE",
        SECOND_END_KEYWORD,
    ),
    accepted_on_purpose(
        Kind::Statements,
        "FOR i := 1 TO 3 DO FOR j := 1 TO 3 DO a := 1; END_FOR END_FOR",
        SECOND_END_KEYWORD,
    ),
];

/// Differences in the expression table.
pub const EXPRESSION_EXCEPTIONS: &[Exception] = &[];

/// Differences in the bodies lifted from the legacy parser tests, against the
/// legacy parser inside a POU.
pub const BODY_EXCEPTIONS: &[Exception] = &[accepted_on_purpose(
    Kind::Statements,
    "\rx := 1;\r",
    LONE_CR,
)];

/// Differences on whole files, against the legacy parser.
pub const FILE_EXCEPTIONS: &[Exception] = &[
    accepted_on_purpose(
        Kind::File,
        "tests/fixtures/lexical/oscat_several_pairs.st",
        OSCAT_SEVERAL_PAIRS,
    ),
    accepted_on_purpose(
        Kind::File,
        "tests/fixtures/lexical/oscat_several_pairs.st (CRLF)",
        OSCAT_SEVERAL_PAIRS,
    ),
    accepted_on_purpose(
        Kind::File,
        "tests/fixtures/lexical/oscat_several_pairs.st (tabs)",
        OSCAT_SEVERAL_PAIRS,
    ),
];

/// Differences in the declarations lifted from the legacy parser tests.
pub const LEGACY_DECLARATION_EXCEPTIONS: &[Exception] = &[
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p\rVAR x : INT; END_VAR\rx := 1;\rEND_PROGRAM\r",
        LONE_CR,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "TYPE {a ? b}\n T : INT;\nEND_TYPE\n",
        PRAGMA_CONTENT,
    ),
];
/// The legacy parser accepts `snippet` and the new one rejects it, on purpose.
const fn rejected_on_purpose(kind: Kind, snippet: &'static str, reason: &'static str) -> Exception {
    Exception {
        kind,
        snippet,
        preset: None,
        legacy: true,
        basis: Basis::Deliberate,
        reason,
    }
}

const LEGACY_ABSTRACT_LABEL: &str = "the legacy label pass does not count the ABSTRACT keyword as a qualifier word, so after `PROPERTY ABSTRACT` or `METHOD ABSTRACT` it reads the declared name followed by `:` as a statement label and rejects the declaration; the CST reads the name by its position in the declaration";
const LEGACY_BARE_NAME_INITIAL: &str = "the legacy grammar rejects an initial value that refers to a variable (`x : INT := name`, `x : INT := a.b`) because it cannot tell a named constant from an enumeration value; CODESYS accepts any expression there (the declaration parser reads the value with its general initialisation rule: Codesys/Parser35220.plugin/CODESYS/Parser35220/Declaration/VariableDeclarationParser.cs:180 and Expressions/InitializationParser.cs:70-92) and decides later whether it is constant. The CST accepts it, the lowering keeps it as an expression, and the analysis folds it or reports it (P4037, P4038)";
const LEGACY_STRING_WIDTH: &str = "the legacy grammar requires a variable's string value to use the declared width's delimiter; the CST accepts either, the lowering gives the value the declared width (as the legacy grammar does for the default of a string type declaration) and the analysis checks its characters against that width (P4052)";
const LEGACY_EMPTY_LIST: &str = "the legacy grammar accepts an empty parenthesised list or an empty bound list where a type needs at least one value or range, and the analysis then misses it for a variable (the inline array is reported only when it is indexed, the empty enumeration not at all). CODESYS rejects both while parsing, at the closing token: the enumeration with `Identifier expected instead of ')'` (Codesys/Parser35220.plugin/CODESYS/Parser35220/Declaration/EnumListParser.cs:261-273) and the array bounds with `Expression expected instead of ']'` (Expressions/OperandParser.cs:481-486 through Declaration/TypeParser.cs:615-625); the CST reports the same syntax error (P0002) at the same token";
const LEGACY_NAMED_GLOBAL_LOCATION: &str = "the legacy global-variable rule takes the name alone and then fails at `AT`, so a global variable with both a name and a location is rejected; the CST accepts the standard `name AT %address : type`";
const LEGACY_DEMOTED_REF_TO: &str = "without `REF_TO` as a keyword the legacy grammar reads `REF_TO INT := NULL` as an enumeration type named REF_TO with the base type INT and the default NULL; the CST reads `REF_TO` as a type name and rejects the extra words";
const VALUE_DOES_NOT_FIT: &str = "the CST grammar takes an array value, a structure value, a qualified enumeration value or a number after an elementary type or an enumeration, where the legacy grammar rejects them; CODESYS parses the value and reports a type error later (Err_UnexpectedArrayInitialisation, Err_UnexpectedStructureInitialisation, Err_NoValidEnumInit), so the lowering reports the value that does not fit the type (P4022)";
const NAMED_ARRAY_VALUE: &str = "the legacy grammar takes an array value only after an inline array type; CODESYS takes it after the name of an array type as well, and the lowering builds an array initial value of the named type";
const ARRAY_OF_REFERENCE_TO_ARRAY: &str = "the CST grammar takes a reference to an array as the element of an array, which the object cannot represent: the lowering rejects it with a syntax error, as the legacy grammar does";

/// Differences in the declaration table.
pub const DECLARATION_EXCEPTIONS: &[Exception] = &[
    accepted_on_purpose(
        Kind::Declarations,
        "FUNCTION_BLOCK fb PROPERTY ABSTRACT p : STRING[4] END_PROPERTY END_FUNCTION_BLOCK",
        LEGACY_ABSTRACT_LABEL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "FUNCTION_BLOCK fb PROPERTY ABSTRACT p : INT END_PROPERTY END_FUNCTION_BLOCK",
        LEGACY_ABSTRACT_LABEL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "FUNCTION_BLOCK fb METHOD ABSTRACT m : INT END_METHOD END_FUNCTION_BLOCK",
        LEGACY_ABSTRACT_LABEL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := y; END_VAR END_PROGRAM",
        LEGACY_BARE_NAME_INITIAL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := name; END_VAR END_PROGRAM",
        LEGACY_BARE_NAME_INITIAL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := a.b; END_VAR END_PROGRAM",
        LEGACY_BARE_NAME_INITIAL,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : STRING[10] := \"ab\"; END_VAR END_PROGRAM",
        LEGACY_STRING_WIDTH,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : MyArray := [1, 2, 3]; END_VAR END_PROGRAM",
        NAMED_ARRAY_VALUE,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "TYPE t : STRUCT a : MyArray := [1, 2]; END_STRUCT; END_TYPE",
        NAMED_ARRAY_VALUE,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "TYPE t : ARRAY[1..2] OF REF_TO ARRAY[1..2] OF INT; END_TYPE",
        ARRAY_OF_REFERENCE_TO_ARRAY,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := [1, 2]; END_VAR END_PROGRAM",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := (a := 1); END_VAR END_PROGRAM",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : INT := Color#Red; END_VAR END_PROGRAM",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : (A, B) := 5; END_VAR END_PROGRAM",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : (A, B) := (a := 1); END_VAR END_PROGRAM",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "TYPE t : (A, B) := 5; END_TYPE",
        VALUE_DOES_NOT_FIT,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : STRING[10] := \"abc\"; END_VAR END_PROGRAM",
        LEGACY_STRING_WIDTH,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : (); END_VAR END_PROGRAM",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : ARRAY[] OF INT; END_VAR END_PROGRAM",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "TYPE t : ARRAY[] OF INT; END_TYPE",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "TYPE t : STRUCT a : (); END_STRUCT; END_TYPE",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "TYPE t : STRUCT a : ARRAY[] OF INT; END_STRUCT; END_TYPE",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR x : REF_TO ARRAY[] OF INT; END_VAR END_PROGRAM",
        LEGACY_EMPTY_LIST,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "PROGRAM p VAR_IN_OUT x : ARRAY[] OF INT; END_VAR END_PROGRAM",
        LEGACY_EMPTY_LIST,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "VAR_GLOBAL g AT %MW0 : INT; END_VAR",
        LEGACY_NAMED_GLOBAL_LOCATION,
    ),
    accepted_on_purpose(
        Kind::Declarations,
        "VAR_GLOBAL g AT %I* : INT; END_VAR",
        LEGACY_NAMED_GLOBAL_LOCATION,
    ),
    rejected_on_purpose(
        Kind::Declarations,
        "TYPE t : REF_TO INT := NULL; END_TYPE",
        LEGACY_DEMOTED_REF_TO,
    ),
];
