//! Whole-file snippets for the types and initial values: one row for each
//! pair of the form of a type and the kind of a value that a declaration of a
//! type, of a structure member or of a variable is built from, accepted and
//! rejected, and one for each element of an initializer.
//!
//! The declaration table holds the forms of the grammar; these rows hold what
//! the lowering decides on top of them. Each is compared as a declaration
//! (the new parser accepts what the legacy parser accepts) and lowered and
//! compared to the legacy object.

pub const TYPES: &[&str] = &[
    // ---- Type declarations, one row each.
    "TYPE t : STRING[10]; END_TYPE",
    "TYPE t : STRING[10] := 'ab'; END_TYPE",
    "TYPE t : WSTRING(10) := \"ab\"; END_TYPE",
    "TYPE t : WSTRING[10] := 'ab'; END_TYPE",
    "TYPE t : STRING[n] := 'ab'; END_TYPE",
    "TYPE t : ARRAY[1..3] OF INT; END_TYPE",
    "TYPE t : ARRAY[-1..+1, lo..hi] OF INT := [1, -2, 3]; END_TYPE",
    "TYPE t : ARRAY[1..9] OF INT := [1, 2.5, TRUE, 'a', T#5s, 3(7), 2(), Red, Color#Green]; END_TYPE",
    "TYPE t : ARRAY[*] OF INT; END_TYPE",
    "TYPE t : ARRAY[1..2] OF STRING[5]; END_TYPE",
    "TYPE t : ARRAY[1..2] OF WSTRING; END_TYPE",
    "TYPE t : ARRAY[1..2] OF REF_TO INT; END_TYPE",
    "TYPE t : ARRAY[1..2] OF REF_TO ARRAY[1..2] OF INT; END_TYPE",
    "TYPE t : PARAMS(3) OF INT; END_TYPE",
    "TYPE t : PARAMS(n) OF STRING; END_TYPE",
    "TYPE t : INT(1..10); END_TYPE",
    "TYPE t : UINT(-3..+3) := -1; END_TYPE",
    "TYPE t : STRUCT a : INT := 5; b : REAL; END_STRUCT; END_TYPE",
    "TYPE t : UNION a : INT; b : REAL; END_UNION; END_TYPE",
    "TYPE t : Point := (x := 1, y := (z := 2), a := [1, 2], e := Color#Red, n := name, k := 1 + 2, m := -5); END_TYPE",
    "TYPE t : (A, B := 2, C := -1) BYTE := B; END_TYPE",
    "TYPE t : (Red, Green) := Color#Red; END_TYPE",
    "TYPE t : Color := Red; END_TYPE",
    "TYPE t : Color := Color#Red; END_TYPE",
    "TYPE t : INT; END_TYPE",
    "TYPE t : INT := -5; END_TYPE",
    "TYPE t : TOD := TOD#10:00; END_TYPE",
    "TYPE t : STRING := 'a'; END_TYPE",
    "TYPE t : WSTRING; END_TYPE",
    "TYPE t : Alias := 5; END_TYPE",
    "TYPE t : REF_TO INT; END_TYPE",
    "TYPE t : REFERENCE TO ARRAY[1..2] OF INT; END_TYPE",
    "TYPE t : POINTER TO STRING; END_TYPE",
    "TYPE t : Other; END_TYPE",
    "TYPE a : INT; b : REAL; END_TYPE TYPE c : (X, Y); END_TYPE",
    // A value that does not fit the type: the grammar accepts it where the
    // position takes a constant, and the lowering reports it.
    "TYPE t : (A, B) := 5; END_TYPE",
    "TYPE t : PARAMS(3) OF INT := 5; END_TYPE",
    "TYPE t : ARRAY[1..2] OF INT := 5; END_TYPE",
    // ---- Initial values of members of a structure.
    "TYPE t : STRUCT a : INT; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : STRING; b : WSTRING[3] := \"ab\"; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : ARRAY[1..2] OF INT := [1, 2]; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : (X, Y); b : (X, Y) := Y; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : INT(0..5); b : INT(0..5) := 3; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : Other; b : Other := (c := 1); d : Other := Red; e : Other := Other#Red; f : Other := 5; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : MyArray := [1, 2]; END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : INT := name; END_STRUCT; END_TYPE",
    // ---- Initial values of variables, one row for each pair.
    "PROGRAM p VAR x : ARRAY[1..3] OF INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : ARRAY[1..3] OF INT := [1, 2, 3]; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : ARRAY[*] OF INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyArray := [1, 2, 3]; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : STRING; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : STRING[10] := 'ab'; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : WSTRING(10) := \"ab\"; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : STRING[10] := \"ab\"; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : REF_TO INT := NULL; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : POINTER TO my_type := REF(y.z); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : PARAMS(3) OF INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, B); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, B) := A; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, B) := T#A; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType; y, z : MyType; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType := (a := 1, b := -2, c := 1.5, d := (e := 3), f := [1, 2], g := Color#Red, h := name, i := 1 + 2, j := -TRUE, k := (5), l := f(1), m := x.y); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType := Red; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType := MyType#Red; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType := 5; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyType := 1 + 2; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := 5; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := -5; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : REAL := -1.5; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : TIME := -T#5s; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : BOOL := -TRUE; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := 1 + 2; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := name; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := a.b; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyBlock(a := 1, 2); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : MyBlock(); END_VAR END_PROGRAM",
    "PROGRAM p VAR_TEMP x : MyType; y : INT := 5; END_VAR END_PROGRAM",
    "FUNCTION f : INT VAR x : MyType := Red; y : ARRAY[1..2] OF INT := [1, 2]; END_VAR f := 1; END_FUNCTION",
    "FUNCTION_BLOCK fb VAR_INPUT a : STRING[3] := 'ab'; END_VAR VAR_OUTPUT b : INT := 5; END_VAR END_FUNCTION_BLOCK",
    // A value that does not fit the type: the grammar accepts it where the
    // position takes an expression, and the lowering reports it.
    "PROGRAM p VAR x : INT := [1, 2]; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := (a := 1); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : INT := Color#Red; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, B) := 5; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, B) := (a := 1); END_VAR END_PROGRAM",
    // ---- Empty lists: a type needs at least one value or one range.
    "TYPE t : (); END_TYPE",
    "TYPE t : (A, ); END_TYPE",
    "TYPE t : ARRAY[] OF INT; END_TYPE",
    "TYPE t : ARRAY[1..2, ] OF INT; END_TYPE",
    "TYPE t : STRUCT a : (); END_STRUCT; END_TYPE",
    "TYPE t : STRUCT a : ARRAY[] OF INT; END_STRUCT; END_TYPE",
    "PROGRAM p VAR x : (); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : (A, ); END_VAR END_PROGRAM",
    "PROGRAM p VAR x : ARRAY[] OF INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR x : REF_TO ARRAY[] OF INT; END_VAR END_PROGRAM",
    "PROGRAM p VAR_IN_OUT x : ARRAY[] OF INT; END_VAR END_PROGRAM",
];
