using _3S.CoDeSys.Core.Components;

namespace _3S.CoDeSys.LanguageModelManager.InternalInterfaces
{
	[TypeGuid("{05CC213D-D203-4f36-A8E0-4DF9443BF6EE}")]
	public enum PragmaOperator
	{
		[ReleasedEnumMember]
		None,
		[ReleasedEnumMember]
		flow,
		[ReleasedEnumMember]
		noflow,
		[ReleasedEnumMember]
		bp,
		[ReleasedEnumMember]
		nobp,
		[ReleasedEnumMember]
		pos,
		[ReleasedEnumMember]
		bpdef,
		[ReleasedEnumMember]
		succ,
		[ReleasedEnumMember]
		error,
		[ReleasedEnumMember]
		warning,
		[ReleasedEnumMember]
		info,
		[ReleasedEnumMember]
		text,
		[ReleasedEnumMember]
		attribute,
		[ReleasedEnumMember]
		define,
		[ReleasedEnumMember]
		undefine,
		[ReleasedEnumMember]
		include,
		[ReleasedEnumMember]
		defined,
		[ReleasedEnumMember]
		variable,
		[ReleasedEnumMember]
		type,
		[ReleasedEnumMember]
		task,
		[ReleasedEnumMember]
		xref,
		[ReleasedEnumMember]
		resource,
		[ReleasedEnumMember]
		from,
		[ReleasedEnumMember]
		pou,
		[ReleasedEnumMember]
		hastype,
		[ReleasedEnumMember]
		hasattribute,
		[ReleasedEnumMember]
		hasvalue,
		[ReleasedEnumMember]
		hasconstantvalue,
		[ReleasedEnumMember]
		opimplicit,
		[ReleasedEnumMember]
		on,
		[ReleasedEnumMember]
		off,
		[ReleasedEnumMember]
		messageguid,
		[ReleasedEnumMember]
		assign,
		[ReleasedEnumMember]
		assert,
		[ReleasedEnumMember]
		show_compile,
		[ReleasedEnumMember]
		show_precompile,
		[ReleasedEnumMember]
		If,
		[ReleasedEnumMember]
		Elsif,
		[ReleasedEnumMember]
		Else,
		[ReleasedEnumMember]
		EndIf,
		[ReleasedEnumMember]
		LeftParenthesis,
		[ReleasedEnumMember]
		RightParenthesis,
		[ReleasedEnumMember]
		Colon,
		[ReleasedEnumMember]
		Or,
		[ReleasedEnumMember]
		And,
		[ReleasedEnumMember]
		Not,
		[ReleasedEnumMember]
		Period,
		[ReleasedEnumMember]
		Comma,
		[ReleasedEnumMember]
		True,
		[ReleasedEnumMember]
		False,
		[ReleasedEnumMember]
		InternalPointerOp,
		[ReleasedEnumMember]
		CompilerVersionPragma,
		[ReleasedEnumMember]
		isenumtype,
		[ReleasedEnumMember]
		allowpaths,
		[ReleasedEnumMember]
		disable,
		[ReleasedEnumMember]
		restore,
		[ReleasedEnumMember]
		fatalerror,
		[ReleasedEnumMember]
		bp2,
		[ReleasedEnumMember]
		nobp2,
		[ReleasedEnumMember]
		RuntimeVersionPragma,
		[ReleasedEnumMember]
		hasconstanttype,
		[ReleasedEnumMember]
		project_defined
	}
}
